import './ui-kit.styl'
import '../../components/main/main.js'
import '../../components/small-components/ui-page-1/ui-wrap/ui-wrap.js'
import '../../components/form-hotel-search/form-hotel-search.js'
import '../../components/small-components/dropdown//img/icon-dropdown.svg'